spring.application.name=notification-service
server.port=8084

# Mailtrap configuration (free tier)
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=your_mailtrap_username
spring.mail.password=your_mailtrap_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger UI configuration
springdoc.swagger-ui.path=/swagger-ui.html
