spring.application.name=notification-service
server.port=8084

# Désactiver complètement JPA/DB
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# Mail Brevo
spring.mail.host=${MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin email
app.admin.email=${ADMIN_EMAIL:azlinedlopes@gmail.com}

# Actuator
management.endpoints.web.exposure.include=health,info
management.health.db.enabled=false

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://app-accessmap.netlify.app}
